# Generated by Django 4.0.3 on 2022-03-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancies', models.IntegerField()),
                ('glucose', models.IntegerField()),
                ('bloodPressure', models.IntegerField()),
                ('skinThickness', models.IntegerField()),
                ('insulin', models.IntegerField()),
                ('bmi', models.DecimalField(decimal_places=1, max_digits=3)),
                ('diabetesPedigreeFunction', models.DecimalField(decimal_places=3, max_digits=4)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
